# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Smart Thermostat
version: "0.0.9"
slug: smart_thermostat
description: The Home Assistant smart thermostat
url: "https://github.com/s7hamachinelearning/smartthermostat"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
image: "ghcr.io/s7hamachinelearning/{arch}-smart-thermostat"
options:
  log_level: info
  # climate: null?
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  # climate: device