# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Smart Thermostat
version: "0.0.1"
slug: smart_thermostat
description: The Home Assistant smart thermostat
url: "https://github.com/s7hamachinelearning/smartthermostat"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello this is you smart thermostat speaking"
schema:
  message: "str?"
image: "ghcr.io/s7hamachinelearning/smartthermostat/{arch}-smart-thermostat"