# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Smart Thermostat
version: "0.0.1"
slug: example
description: The HA smart thermostat addon
url: "https://github.com/S7HaMachineLearning/SmartThermostat"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello this is you smart thermostat speaking"
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-example"
